# Generated by Django 6.1.1 on 2026-10-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_DB',
            fields=[
                ('VEh_No', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('VehName', models.CharField(max_length=20)),
                ('DoB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Mobile', models.IntegerField()),
            ],
        ),
    ]
